### ISSUE TITLE
DirectX9 and DotNet4 support?

### ISSUE THREAD

**Issue by lexterror** [akbarri/ExaTerm#1]
Hi, 

I'm really glad you have this project going! I actually bought exagear from the playstore a few years ago and then saw a mod after the company disappeared. I just found an exagear mod two days ago that has dx9 and dotnet4! I thought you may want to know! And it works pretty well!

https://platinmods.com/threads/exagear-windows-emulator-3-0-2-exteme-mod.126731/

Thank you!

**Comment by akbarri** [comment]
Thank You FYI.
I will Try it.
